version: "3.9"

services:
  core:
    platform: linux/x86_64  # https://github.com/GrahamDumpleton/wrapt/issues/199#issuecomment-1054696160
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./data/cache:/data
