version: "3.9"

services:
  core:
    platform: linux/x86_64  # https://github.com/GrahamDumpleton/wrapt/issues/199#issuecomment-1054696160
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=szadmin
      - POSTGRES_PASSWORD=szadmin1234

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=szadmin
      - POSTGRES_PASSWORD=szadmin1234
      - PGDATA='/var/lib/postgresql/data'
