version: "3.9"

services:
  core:
    platform: linux/x86_64  # https://github.com/GrahamDumpleton/wrapt/issues/199#issuecomment-1054696160
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - ../src/config/.env.local

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/etc/mongo
    env_file:
      - ../src/config/.env.local
